# Generated by Django 4.2 on 2023-04-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogger_info', '0006_remove_users_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key='True', serialize=False, unique=True)),
                ('post_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of blog post')),
                ('post_image', models.ImageField(blank=True, default='static/images/avatar.jpg', null=True, upload_to='posts/%Y/%m/%d', verbose_name='Blog post picture')),
                ('post_body', models.TextField(blank=True, null=True, verbose_name='body of user')),
                ('votes_total', models.IntegerField(blank=True, default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogger_info.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'UP VOTE'), ('down', 'DOWN VOTE')], max_length=200)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('blogpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tags', verbose_name='Tags seperated by #'),
        ),
    ]
