# Generated by Django 4.2 on 2023-04-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.tags', verbose_name='Tags seperated by #'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
