# Generated by Django 4.2 on 2023-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_tags_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tags', verbose_name='Tags seperated by #'),
        ),
    ]
