# Generated by Django 4.2 on 2023-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
