# Generated by Django 4.2 on 2023-04-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blogpost_votes_ratio_comments_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
