# Generated by Django 4.2 on 2023-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_comments_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='votes_ratio',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='votes_total',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='value',
        ),
    ]
